account_id = "2bd99d5b13b2186382cd3dc995b0bb18"
name = "healthlog-ai"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "HEALTHLOG_KV"
id = "526fcd4e482943f2bc9b958613dcd6fa"

[vars]
AGENT_NAME = "HealthLog"
AGENT_TONE = "empathetic, cautious, evidence-based"
AGENT_AVATAR = "💊"

[[kv_namespaces]]
binding = "KG"
id = "c7886204c80845c6b9568693ed277b75"
